quarkus:
  datasource:
    db-kind: postgres
    jdbc:
      driver: org.postgresql.Driver
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    migrate-at-start: true
    validate-migration-naming: true
  http:
    cors:
      enabled: true
      allow-origin: "http://localhost:63342"
      allow-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
      allow-headers: [ "Content-Type", "Authorization"]
      exposed-headers: [ "Content-Type", "Authorization" ]
  log:
    level: INFO
    category:
      "org.sergiorebelo.piupiu.usermanagement.*": TRACE
    file:
      enable: true
      path: logs/myapp.log